import {
  AlertCircleIcon,
  BanknoteIcon,
  BellIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BuildingIcon,
  CalendarIcon,
  CarIcon,
  ClipboardListIcon,
  CreditCardIcon,
  FactoryIcon,
  FlagIcon,
  GiftIcon,
  GraduationCapIcon,
  HeartIcon,
  HomeIcon,
  LandmarkIcon,
  type LucideIcon,
  MailPlusIcon,
  MegaphoneIcon,
  MessageSquareIcon,
  NewspaperIcon,
  PackageIcon,
  PenLineIcon,
  PlaneIcon,
  ReceiptIcon,
  ShieldIcon,
  ShoppingCartIcon,
  SnowflakeIcon,
  SparklesIcon,
  StarIcon,
  TagIcon,
  TicketIcon,
  TrendingUpIcon,
  UsersIcon,
  WrenchIcon,
} from "lucide-react";

// Icons a label can use in the sidebar. Keys are stored in Label.icon, so
// renaming a key orphans saved picks — add new entries instead of renaming.
export const LABEL_ICONS: Record<string, LucideIcon> = {
  tag: TagIcon,
  calendar: CalendarIcon,
  snowflake: SnowflakeIcon,
  users: UsersIcon,
  factory: FactoryIcon,
  "message-square": MessageSquareIcon,
  "mail-plus": MailPlusIcon,
  megaphone: MegaphoneIcon,
  bell: BellIcon,
  package: PackageIcon,
  "trending-up": TrendingUpIcon,
  "graduation-cap": GraduationCapIcon,
  "pen-line": PenLineIcon,
  receipt: ReceiptIcon,
  "credit-card": CreditCardIcon,
  banknote: BanknoteIcon,
  landmark: LandmarkIcon,
  briefcase: BriefcaseIcon,
  building: BuildingIcon,
  "clipboard-list": ClipboardListIcon,
  newspaper: NewspaperIcon,
  "shopping-cart": ShoppingCartIcon,
  gift: GiftIcon,
  ticket: TicketIcon,
  plane: PlaneIcon,
  car: CarIcon,
  home: HomeIcon,
  heart: HeartIcon,
  star: StarIcon,
  flag: FlagIcon,
  shield: ShieldIcon,
  wrench: WrenchIcon,
  "book-open": BookOpenIcon,
  sparkles: SparklesIcon,
  "alert-circle": AlertCircleIcon,
};

export function getLabelIcon(name: string | null | undefined): LucideIcon {
  if (name && LABEL_ICONS[name]) return LABEL_ICONS[name];
  return TagIcon;
}
